test:
  name: pbft-network
  description: pbft-network
  workers:
    type: local
    number: 5

  rounds:
  - label: transfer
    description: transfer
    txNumber: 2000
    rateControl:
      type: fixed-rate
      opts:
        tps: 100
    callback: ../chaincode/demo/callback/transfer.js

  - label: Trading
    description: Trading
    txNumber: 2000
    rateControl:
      type: fixed-rate
      opts:
        tps: 100
    callback: ../chaincode/demo/callback/Trading.js

monitor:
  interval: 1
  type: 
    - docker
  docker:
    containers:
    - peer0.orga.com
    - orderer0.yzm.com
    - orderer1.yzm.com
    - orderer2.yzm.com
    - orderer3.yzm.com
